### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by preguntoncojonero** [ctt-gob-es/FirmaXadesNet45#1]
Hola, muy buen trabajo! Un proyecto muy interesante en C#.

Con su aplicación, es posible seleccionar el certificado de DNIe (de autenticación, AC RAIZ DNIE) y realizar la validación OCSP?

Desde mi ignorancia y torpeza, es poco lo que he encontrado en C# sobre estos temas de Firma, DNIe, Facturae (FACe)...a mi me suena a chino, y ando muy perdido.

Existe una aplicación @firma para temas de firma, esos son los formatos que maneja:

https://valide.redsara.es/valide/faqs.html#1
Actualmente el cliente permite realizar firmas en múltiples formatos diferentes como PKCS#7, CMS, CADES, XMLDSig, XADES y PADES.

Formato XAdES (XML Advanced Electronic Signatures), según especificación ETSI TS 101 903.
Formato CAdES (CMS Advanced Electronic Signatures), según especificación ETSI TS 101 733.
Formato PAdES (PDF Advanced Electronic Signatures), según especificación ETSI TS 102 778-2 y ETSI TS 102 778-3.

Luego está http://www.facturae.es, que tendrá sus formatos.

Qué evolución tendrá su aplicación ? incluirá más formatos de firma?

Saludos y muchas gracias!

**Comment by dnturbanismo** [comment]
Buenas,

Puedes echarle un vistazo a la clase OcspClient para el tema de la validación de certificados, incluso podrías copiar la clase a tu proyecto y añadir las librerías Bouncy Castle para utilizarla y así no te haría falta utilizar la librería al completo si lo único que necesitas es validar certificados.

En cuanto al tema del roadmap no está previsto añadir otros formatos de firma, ya que no disponemos del tiempo ni los recursos necesarios, si necesitas realizar firmas en otros formatos desde .NET creo que tendrás que utilizar otras librerías para los demás formatos de firma, por ejemplo con iTextSharp puedes generar firmas PAdES... como curiosidad puedes consultar el siguiente repositorio:

https://github.com/nonorganic/dssnet

Es bastante interesante por que permite realizar firmas XAdES y CAdES, yo estuve intentando acoplar nuestra librería junto con iTextSharp para poder realizar todos los tipos de firma, y aunque es bastante trabajo yo creo que podría dar resultado.

Espero que te sirva de ayuda, un saludo.
