### ISSUE TITLE
How to remove a document signature?

### ISSUE THREAD

**Issue by dmitriy-shleht** [ctt-gob-es/FirmaXadesNet45#4]
**How can I delete one or more document signatures?**
```cs
var xadesService = new XadesService();
var signatureDocs = xadesService.Load(xml)

signatureDoc.Length // 3
```
Thank you!

**Comment by dnturbanismo** [comment]
Unfortunately the library has no method to delete signatures, but you can search in your XML the signature nodes and delete it.

Try this:

`
XmlNode xmlNode = xmlDocument.SelectSingleNode("//*[@Id='" + signatureId + "']");
xmlNode.ParentNode.RemoveChild(xmlNode);
`

**Comment by dmitriy-shleht** [comment]
Thanks!
